language: python

python:
  - 3.5

services:
  - xvfb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - libstdc++6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U protobuf

install:
  - pip install ./Project_Navigation
  - python ./Project_Navigation/environment/download_environment.py
  - pip install ./Project_ContinuousControl
  - python ./Project_ContinuousControl/environment/download_environment.py
  - pip install ./Project_CollaborationCompetition
  - python ./Project_CollaborationCompetition/environment/download_environment.py

script:
  - python -m pytest ./Project_Navigation
  - python -m pytest ./Project_ContinuousControl
  - python -m pytest ./Project_CollaborationCompetition

notifications:
  email: false
