language: python

python:
  - 3.5

services:
  - xvfb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - libstdc++6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U protobuf

install:
  - pip install -e Project_Navigation

script:
  - cd Project_Navigation/environment
  - python download_environment.py
  - cd ..
  - pytest

notifications:
  email: false
