language: python

python:
  - 3.5

services:
  - xvfb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - libstdc++6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U protobuf

install:
  - pip install Project_Navigation
  - pip install Project_ContinuousControl

script:
  - pytest

notifications:
  email: false
