DEFAULT_HYPERPARAMETERS = {
    "DNN_ARCHITECTURE": [512, 256],
    "LEARNING_RATE_ACTOR": 1e-3,
    "LEARNING_RATE_CRITIC": 1e-4,
    "GAMMA": 0.99,
    "GRADIENT_CLIPPING_MAX": 1.0,
    "BATCH_SIZE": 512,
    "BUFFER_SIZE": int(1e6),
    "TAU": 0.02,
    "WEIGHT_DECAY": 0.0001,
    "STEPS_BETWEEN_LEARNING": 2,
    "EPSILON_START": 1.0,
    "EPSILON_END": 0.1,
    "EPSILON_DECAY": 5e-6,
    "NOISE_SIGMA": 0.5,
    "WARM_UP_EPISODES": 300
}
